### ISSUE TITLE
Pergunta 1

### ISSUE THREAD

**Issue by bmarchete** [MarrentaxD/ProjetoMDBD#1]
Mostre Quantos Times é patrocinado por ISMA

Não entendi o que é ISMA? Vocês podem explicar :boom:

**Comment by ksamill** [comment]
ISma é uma empresa

**Comment by MarrentaxD** [comment]
ISMA é um Patrocinador :ear:

**Comment by bmarchete** [comment]
Ah, acho que a solução é esta

```sql
select * from empresas
```
😆

**Comment by MarrentaxD** [comment]
:+1:
