### ISSUE TITLE
Questão 3

### ISSUE THREAD

**Issue by Paulo-Henrique-Schiavetti** [MarrentaxD/ProjetoMDBD#10]
questo, porque não é muito grande para ser um questão!

**Comment by Paulo-Henrique-Schiavetti** [comment]
eu verifico o total de gol para saber quantos gols o time fez?

**Comment by Paulo-Henrique-Schiavetti** [comment]
levantando essa questão novamente, o total não recebe os gols da tabela resultado_jogos, só pra deixar aqui mesmo.

**Comment by MarrentaxD** [comment]
Sim, você precisa verificar o total de gols para saber quantos gols determinado time marcou. :shipit:

**Comment by Paulo-Henrique-Schiavetti** [comment]
boa noite :princess: e obrigado

**Comment by jpfs2001** [comment]
Acho que a resposta é

```sql
 SELECT id_time, nome_time, MAX(total_Gols) as gols, pontos FROM testecampeonato.classificacao;

```

**Comment by MarrentaxD** [comment]
:+1:

**Comment by jpfs2001** [comment]
:+1:

**Comment by MarrentaxD** [comment]
:+1:

**Comment by bmarchete** [comment]
Corrigir esta questão!

**Comment by MuCaMartins** [comment]
```sql select sum(gols), times_id from mydb.tabela group by times_id order by 'desc'; ```
Correção da questão 3
