### ISSUE TITLE
questão 5

### ISSUE THREAD

**Issue by Paulo-Henrique-Schiavetti** [MarrentaxD/ProjetoMDBD#13]
abri a issue e saí correndo,
pau no cy de quem ta lendo.

**Comment by bmarchete** [comment]
O legal é que dá pra saber que foi o Paulo que escreveu isso!!
Quem será que merece uma nota bem bacana? @Paulo-Henrique-Schiavetti

**Comment by Paulo-Henrique-Schiavetti** [comment]
agora, indo à questão, na classificação eu posso acessar o total de gols certo?

**Comment by MarrentaxD** [comment]
Sim :shipit:

**Comment by bmarchete** [comment]
Alguem pode fechar essa issue por favor?

**Comment by MarrentaxD** [comment]
:+1:
