### ISSUE TITLE
Oi

### ISSUE THREAD

**Issue by jpfs2001** [MarrentaxD/ProjetoMDBD#3]

**Comment by jpfs2001** [comment]
Eu não sou estoque

**Comment by jpfs2001** [comment]
alguem ai pra me responder?

**Comment by MuCaMartins** [comment]
Boa tarde :smile_cat:

**Comment by jpfs2001** [comment]
:joy_cat: :joy_cat: :joy_cat: :joy_cat: :joy_cat: :joy_cat:

**Comment by jpfs2001** [comment]
:octocat::octocat::octocat::octocat:

**Comment by jpfs2001** [comment]
Alguém me explica pq eu dormi no sofá e acordei no lixo

**Comment by jpfs2001** [comment]
:cat2:

**Comment by MuCaMartins** [comment]
Por que ninguém gosta de você, palhaço :clown_face:

**Comment by jpfs2001** [comment]
:(

**Comment by MuCaMartins** [comment]
Favor realizar perguntas construtivas :pick:

**Comment by MuCaMartins** [comment]
Do u know Marcelo David "Coldzera" ?

**Comment by Rafaell17** [comment]
Oi murilo
