### ISSUE TITLE
Problema nos inserts

### ISSUE THREAD

**Issue by jpfs2001** [MarrentaxD/ProjetoMDBD#4]
# Para comentar no SQL, não se usa // mas sim -- "Comentário" -- (Retire as aspas).

**Comment by Rafaell17** [comment]
oi

**Comment by MuCaMartins** [comment]
Maneiro fera, agradecemos sua opinião consertaremos em breve :handshake:

**Comment by Paulo-Henrique-Schiavetti** [comment]
flop

**Comment by Rafaell17** [comment]
Desculpe senhor, Consertaremos o problema :dancer:

**Comment by Paulo-Henrique-Schiavetti** [comment]
"pratrocinadores"
