### ISSUE TITLE
campo times_id da tabela resultados_jogos...

### ISSUE THREAD

**Issue by Paulo-Henrique-Schiavetti** [MarrentaxD/ProjetoMDBD#5]
o campo times_id da tabela resultado_jogos é necessario, já existiam os campos time1_id e time2_id na tabela jogam, vocês vão por dois times em um campo só?

**Comment by Nawanzera** [comment]
No campo times id são os ID dos times em geral, já na tabela jogam são apenas os ID dos times que irão jogar! :full_moon_with_face:

**Comment by MuCaMartins** [comment]
É necessário, pois é preciso especificar qual jogo aconteceu, em cada partida para coloca-la na tabela " Classificação "

**Comment by Rafaell17** [comment]
A cada resultado necessita do ID de dois times diferentes para cada jogo

**Comment by Paulo-Henrique-Schiavetti** [comment]
não intendir mas tudo bem!:disappointed::joy::joy::joy:

**Comment by MuCaMartins** [comment]
É necessário usá-la meu caro

**Comment by Nawanzera** [comment]
Seguinte, é necessário times_id da tabela resultado para que mostre o resultado da partida, já os ids do time 1 e 2 da tabela jogam são apenas para mostrar os jogos que serão realizados! :boom:
