### ISSUE TITLE
o campo gol

### ISSUE THREAD

**Issue by Paulo-Henrique-Schiavetti** [MarrentaxD/ProjetoMDBD#6]
o campo gol da tabela resultado_jogos vai receber os gols dos dois times?

**Comment by MuCaMartins** [comment]
Isso, será inserido os gols dos 2 times que jogaram

**Comment by MuCaMartins** [comment]
ID_jogo - time_ID - Gols
 
1              2               4
1              3               5 

O time 2 marcou 4 gols, enquanto o time 3 marcou 5

**Comment by Paulo-Henrique-Schiavetti** [comment]
os gols totais de um time devem ser digitados manualmente? ou já vai automaticamente?:neckbeard::heart_eyes::stuck_out_tongue_winking_eye:

**Comment by MuCaMartins** [comment]
Eles já estão inseridos automaticamente no arquivo " Inserts.txt " :paperclip:

**Comment by MuCaMartins** [comment]
O resultado foi respondido, pré determinadamente

**Comment by MuCaMartins** [comment]
Boa tarde, volte sempre <3
